name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.12]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      run: |
        sudo apt-get install -y python${{ matrix.python-version }}
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ matrix.python-version }} 1
        sudo update-alternatives --set python3 /usr/bin/python${{ matrix.python-version }}
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev

    - name: Run Tests
      run: |
        pipenv run python Backend/manage.py test
